# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Parrybytes"
description: "Cybersecurity, with less doom and gloom and more 'Ah, I get it now!'"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parrybytes.cloud" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/cuttlefish-Logo.png"
favicon_ico: "/assets/images/favicon-32x32.png"
search: true
lunr:
  search_within_pages: true



plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-archives
 - jekyll-remote-theme
 - jekyll-paginate
 - jekyll-include-cache
 - jekyll-gist

social:
  linkedin: "https://www.linkedin.com/in/scottjparry" 

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "dark"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scottjparry"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/scottjparry"

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# <img src="/assets/images/bio/Scott.png">
# Site Author
author:
  name             : "Scott Parry"
  avatar           : "/assets/images/bio/Scott.png"
  # avatar           : "<img src='/assets/images/bio/Scott.png'>"
  bio              : "I make compliance useful, not ornamental. Your auditors will love it. Your engineers might even respect it."
  location         : "Australia"
  email            :
      - label: "Email"
        icon: "fas fa-fw fa-envelope-square"
        url: "mailto:scott@parrybytes.cloud"
      - label: "Website"
        icon: "fas fa-fw fa-link"
        url: "https://parrybytes.com"
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://linkedin.com/in/scottjparry"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      author: Scott Parry
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      author: Scott Parry
    # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

include:
  - "_pages"
  
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomya
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
