# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Parrybytes"
email: scott@parrybytes.cloud
description: >- # this means to ignore newlines until "baseurl:"
   Cybersecurity, with less doom and gloom and more "Ah, I get it now!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parrybytes.cloud/" # the base hostname & protocol for your site, e.g. http://example.com


plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
just_the_docs:
  nav_depth: 2

color_scheme: dark

title: "Parrybytes: Cloud Security Insights & Cybersecurity Strategies by Scott J Parry"
description: "Parrybytes is my digital hub for cloud security insights, cybersecurity thought leadership, and modern IT governance strategies, blending practical expertise with forward-thinking analysis."
url: "https://parrybytes.cloud"  # Your custom domain URL
social:
  linkedin: "https://www.linkedin.com/in/scottjparry" 

# Just the Docs settings
search_enabled: true
aux_links:
  "View on GitHub":
    - "//github.com/scottjparry"
  "Find me on LinkedIn":
    - "//linkedin.com/scottjparry"

remote_theme: "just-the-docs/just-the-docs"

footer_content: 'Copyright &copy; 2025 Scott Parry. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a> <a href="https://www.just-the-docs.com/">This site is powered by Just-The-Docs on GitHub Pages.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html