name: GitHub Pages

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*"  # Trigger on any change; adjust if you wish to limit to specific folders

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
      
      - name: Build site with Jekyll
        run: bundle exec jekyll build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v3
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          branch: gh-pages   # This is the branch GitHub Pages will use for deployment
          folder: _site